name: 'flutter_lucid_bell'
description: 'Simplest interval bell to remind you what you want'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.12
  package_info_plus: ^3.0.3
  syncfusion_flutter_sliders: ^20.4.49
  workmanager: ^0.5.1
  assets_audio_player: ^3.0.6
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  watcher: ^1.0.2
  google_fonts: ^4.0.3
  intl: ^0.18.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sound/
    - assets/fonts/


  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
